calificaciones/bases/urls.py
from django.urls import include, path
from calificaciones.bases.views import *
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="bases/login.html"),name='logout'),
    path('register/',UserNew.as_view(),name="register"),
    path('sin_privilegios/',HomeSinPrivilegios.as_view(),name="sin_privilegios")
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    #path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path('',include(('calificaciones.bases.urls','bases'),namespace='bases')),
    path('materias',include(('calificaciones.materias.urls','materias'),namespace='materias')),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("calificaciones.users.urls", namespace="users")),
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# API URLS
urlpatterns += [
    # API base url
    #path("api/", include("config.api_router")),
    # DRF auth token
    #path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

calificaciones/bases/models.py
from django.db import models
from calificaciones.users.models import User

class ClaseModelo(models.Model):
    estado= models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User,on_delete=models.CASCADE)
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract=True

calificaciones/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth import get_user_model
from django.utils import timezone

from django.contrib.auth.hashers import make_password


class AccountManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, name, phone, password, **extra_fields):
        values = [email, name, phone]
        field_value_map = dict(zip(self.model.REQUIRED_FIELDS, values))
        for field_name, value in field_value_map.items():
            if not value:
                raise ValueError('The {} value must be set'.format(field_name))

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            name=name,
            phone=phone,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, name, phone, password, **extra_fields)

    def create_superuser(self,email,  name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, name, phone, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(auto_created=True,primary_key=True,unique=True, serialize=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=150,null=True,blank=True)
    phone = models.CharField(max_length=50,null=True,blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    picture = models.ImageField(blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(null=True)
    username = models.CharField(max_length=255, unique=True,null=True,blank=True)
    apellido = models.CharField(max_length=50,null=True,blank=True)
    dni = models.CharField(max_length=10,null=True,blank=True)

    objects = AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'phone']

    def get_full_name(self):
        return self.name

calificaciones/bases/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from calificaciones.users.models import User
from django.core.exceptions import ValidationError
# from calificaciones.users.forms import UserCreationForm


class RegisterForm(forms.ModelForm):
    name = forms.CharField(max_length=50, label="Nombres", widget=forms.TextInput)
    apellido = forms.CharField(max_length=50, label='apellidos', widget=forms.TextInput)
    phone = forms.CharField(max_length=8, label="Telefono", widget=forms.TextInput)
    dni = forms.CharField(max_length=10, label="Cedula de Identidad", widget=forms.TextInput)
    email = forms.EmailField(label='Correo Electronico', widget=forms.EmailInput)
    date_of_birth = forms.DateField(label='Fecha de Nacimiento', widget=forms.DateInput)

    class Meta:
        model = User
        fields = ('name', 'apellido', 'dni', 'phone', 'email', 'date_of_birth', 'picture')

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) > 30:
            raise forms.ValidationError("Los nombres tiene que tener maximo 30 caracteres")
        return name
    def clean_apellido(self):
        apellido = self.cleaned_data.get('apellido')
        if len(apellido) > 30:
            raise forms.ValidationError("Los Apellidos tienen que tener maximo 30 caracteres")
        return apellido

    def clean_dni(self):
        dni = self.cleaned_data.get('dni')
        if len(str(dni)) > 10:
            raise forms.ValidationError("El numero de DNI tiene que tener maximo 10 caracteres")
        else:
            if User.objects.filter(dni=dni).exists():
                raise forms.ValidationError("DNI ya existe")
        return dni
    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if len(str(phone)) > 8:
            raise forms.ValidationError("El nunero de telefono tiene que ser maximo 8 caracteres")
        return phone
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if len(str(email)) < 10:
            raise forms.ValidationError("Introdusca un correo electronico valido")
        else:
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError("Correo electronico ya existe")
        return email

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data.get('date_of_birth')
        if len(str(date_of_birth)) > 10:
            raise forms.ValidationError("Introdusca una fecha valida")
        return date_of_birth

calificaciones/bases/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import *
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import AuthenticationForm
#from django.contrib.auth.forms import UserCreationForm
from calificaciones.bases.forms import RegisterForm
from django import forms
from calificaciones.users.models import User
from django.contrib import messages
# Create your views here.
#def registeruser(request):
#    if request.method == 'POST':
#        form = RegisterForm(request.POST)
#        if form.is_valid():
#            form.save()
#            username = form.cleaned_data.get('username')
#            raw_password  = form.cleaned_data.get('password1')
#            user  = authenticate(username=username,password=raw_password)
#            login = (request,user)
#            return redirect('bases:home')
#        else:
#            form = RegisterForm()
#        return render(request,'register.html',{'form':form})

class SinPrivilegios(LoginRequiredMixin,PermissionRequiredMixin):
    login_url = 'bases:login'
    raise_exception = False
    redirect_field_name = "redirect_to"
    def handle_no_permission(self):
        from django.contrib.auth.models import AnonymousUser
        if not self.request.user == AnonymousUser():
            self.login_url = 'bases:sin_privilegios'
        return HttpResponseRedirect(reverse_lazy(self.login_url))


class HomeSinPrivilegios(LoginRequiredMixin,TemplateView):
    login_url = "bases:login"
    template_name = "bases/sin_privilegios.html"

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            return redirect('bases:home')

    else:
        form = AuthenticationForm()
    return render(request,'bases/login.html',{'form':form})

class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = "bases/login.html"
    success_url =  reverse_lazy("bases:home")
    def form_valid(self, form):
        login(self.request, form.get_user())
        messages.success(self.request, 'Bienvenido')
        return super(LoginView, self).form_valid(form)


class UserNew(CreateView):
    model= User
    template_name="bases/register.html"
   
    form_class= RegisterForm
    success_url = reverse_lazy("bases:login")

    def get_context_data(self, **kwargs):
        context = super(UserNew, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        print (form)
        if form.is_valid() :
            reg = form.save(commit=False)
            reg.is_active = False
            password = reg.dni

            reg.username = reg.dni
            #el set_password me sirve para poder cifrar la contraseña el mismo metodo que usa django
            reg.set_password(password)
            reg.save()
            print( reg.username,reg.password)
            print(request, "se creo ")
            messages.success(request , 'Registro con exito')
            return HttpResponseRedirect(self.get_success_url())
        else:
            #form = {
            #   'name':form.name,
            #   'apellido':form.apellido,
            #   'dni':form.dni,
            #   'phone':form.phone,
            #   'email':form.email,
            #   'date_of_birth':form.date_of_birth,
            #   'picture':form.picture
            #}
            
            return self.render_to_response(self.get_context_data(form=form))


class Home(LoginRequiredMixin, TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'

calificaciones/bases/templates/bases/home.html
{% extends 'base/base.html' %}
{% block page_content %}

   <!-- Basic Examples -->
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
               
            </div>
            <div class="row clearfix">
            
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <div class="row">
                                <div class="col-md-4 col-sm-offset-8">
                                {% if messages %}
                                <ul class="message">
                                    
                                    {% for message in messages %}
                                        <div style="text-align: center" class="alert alert-success {{ message.tags }}  alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <a href="#" class="del-msg">&times;</a>
                                            </button>
                                            {{ message }} &nbsp;{% if user.name %}{{user.name|upper}}{% endif %} &nbsp;{% if user.apellido %} {{user.apellido|upper}}  {% endif %}
                                        
                                        </div>
                                    {% endfor %}
                                    
                                
                                </ul>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                   
                        <div class="body">
                            <div class="image_inner_container text-center">
                                <img src="../../../static/images/feyalegria.png" style="width: 50%;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Examples -->
            </div>

      </section>
      {% endblock page_content %}
      

calificaciones/bases/templates/bases/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Sign In | Bootstrap Based Admin Template - Material Design</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../../static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../../static/plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../../static/plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="../../../static/css/style.css" rel="stylesheet">
</head>
 
<body class="login-page">
              
                       {% if messages %}
                     
                        
                        {% for message in messages %}
                              <div style="text-align: center" class="message alert alert-success {{ message.tags }} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <a href="#" class="del-msg">&times;</a>
                                </button>
                                {{ message }}
                               
                              </div>
                        {% endfor %}
                        
                       
                      
                    {% endif %}
                   
    <div class="login-box" >
        <div class="logo">
            <a href="javascript:void(0);">Admin<b>BSB</b></a>
            <small>Admin BootStrap Based - Material Design</small>
        </div>
        <div class="card">
            <div class="body">
                <form class="user" id="sign_in" method="POST">
                  {% csrf_token %}

                {% for field in form %}
                  {% for error in field.errors %}
                      <div class="alert alert-danger">
                          <strong>{{ error|escape }}</strong>
                      </div>
                  {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}

                  <div class="msg">Sign in to start your session</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="username" id="id_username"  placeholder="Username" required autofocus>
                            <label for="id_username" id="id_username"></label>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="password" id="id_password" placeholder="Password" required>
                            <label for="id_password" id="id_password"></label>
                          </div>
                    </div>


                    <div class="row">

                        <div class=" col-xs-8 p-t-5" >
                            <input type="checkbox" name="rememberme" id="rememberme" class="filled-in chk-col-pink">
                            <label for="rememberme">Remember Me</label>
                        </div>
                        <div class="col-xs-4">
                            <button class="btn btn-block bg-pink waves-effect" type="submit">SIGN IN</button>
                        </div>
                    </div>

                    <div class="row m-t-15 m-b--20">
                        <div class="col-xs-6">
                            <a href="{% url 'bases:register' %}">Register Now!</a>
                        </div>
                        <div class="col-xs-6 align-right">
                            <a href="{% url 'bases:register' %}">Forgot Password?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="../../../static/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../../static/plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../../static/plugins/node-waves/waves.js"></script>

    <!-- Validation Plugin Js -->
    <script src="../../../static/plugins/jquery-validation/jquery.validate.js"></script>
    <script src="../../../static/plugins/jquery-validation/localization/messages_es.js"></script>

    <!-- Custom Js -->

    <script src="../../../static/js/admin.js"></script>
    <script src="../../../static/js/pages/examples/sign-in.js"></script>
    <script>
        $(document).ready(function() {
            // messages timeout for 3 sec 
            setTimeout(function() {
                $('.message').fadeOut('slow');
            }, 3000); // <-- time in milliseconds, 1000 =  1 sec
        });
    </script>
</body>

</html>

calificaciones/bases/templates/bases/register.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Sign Up | Bootstrap Based Admin Template - Material Design</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../../static/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../../static/plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../../static/plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="../../../static/css/style.css" rel="stylesheet">
</head>

<body class="signup-page">
    <div class="signup-box">
        <div class="logo">
            <a href="javascript:void(0);">Admin<b>BSB</b></a>
            <small>Admin BootStrap Based - Material Design</small>
        </div >
        <div class="card">
            <div class="body">
                <form id="sign_up" method="POST" action="{% url 'bases:register' %}">
                 {% csrf_token %}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div style="size: 10px;" class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                    <div class="msg">Register a new membership</div>
                      <div class="input-group">
                          <span class="input-group-addon">
                              <i class="material-icons">account_circle</i>
                          </span>
                          <div class="form-line">
                              <input type="text" class="form-control" name="name" id="id_name" placeholder="Nombres" required autofocus>
                          </div>
                      </div>
                      <div class="input-group">
                          <span class="input-group-addon">
                              <i class="material-icons">account_circle</i>
                          </span>
                          <div class="form-line">

                              <input type="text" class="form-control" name="apellido" id="id_apellido" value="{{obj.apellido}}" placeholder="Apellidos" required>

                            </div>
                      </div>

                      <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">card_membership</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="dni" id="id_dni" placeholder="Cedula Identidad" required >
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">phone</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="phone" id="id_phone" placeholder="Telefono" required>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">email</i>
                        </span>
                        <div class="form-line">
                            <input type="email" class="form-control" name="email" id="id_email" placeholder="Correo Electronico" required >
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">date_range</i>
                        </span>
                        <div class="form-line" >
                            <input type="date" id="datepicker" class="form-control datepicker" name="date_of_birth" id="id_date_of_birth" placeholder="Fecha de Nacimiento" required>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">folder_open</i>
                        </span>
                        <div class="form-line">
                          <div></div>
                            <input type="file" class="form-control" name="picture" id="id_picture"  accept="image/*" placeholder="Foto Perfil" required >
                        </div>
                    </div>

                    <!--<button type="button" class="btn btn-default waves-effect" data-toggle="modal" data-target="#smallModal">MODAL - SMALL SIZE</button>-->
                    <button class="btn btn-block btn-lg bg-pink waves-effect" type="button" data-toggle="modal" data-target="#smallModal">Registrar</button>
                    <div class="modal fade" id="smallModal" tabindex="-1" role="dialog">
                        <div class="modal-dialog modal-sm" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="smallModalLabel">Registrar</h4>
                                </div>
                                <div class="modal-body">
                                    Verifique que sus datos esten correctos!!
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-link waves-effect">Registrarse</button>
                                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">Salir</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="m-t-25 m-b--5 align-center">
                        <a href="{% url 'bases:login' %}">You already have a membership?</a>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="../../../static/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../../static/plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../../static/plugins/node-waves/waves.js"></script>

    <!-- Validation Plugin Js -->
    <script src="../../../static/plugins/jquery-validation/jquery.validate.js"></script>
    <script src="../../../static/plugins/jquery-validation/localization/messages_es.js"></script>

    <!-- Custom Js -->
    <script src="../../../static/js/admin.js"></script>
    <script src="../../../static/js/pages/examples/sign-up.js"></script>
    <script>


    </script>
    <script>
      $(document).ready(function() {
        $('.datepicker').datepicker({
        "setDate": new Date(),
        "autoclose": true
      });
      });
    </script>
</body>

</html>

calificaciones/bases/templates/bases/sin_privilegios.html
{% extends 'base/base.html' %}
{% block page_content %}
<!-- Earnings (Monthly) Card Example -->
<section class="content">
  <div class="container-fluid">
    <div class="block-header">
      <h2><b>SIN PRIVILEGIOS</b></h2>
    </div>
    <!-- Basic Example -->
    <div class="row clearfix">
      <div class="col-lg-5 col-md-6 col-sm-8 col-xs-12">
        <div class="card">
          <div class="header bg-red">
            <h2>
              Usuario: <b> {{ user.username}} {{user.get_full_name}}</b> </h2>

          </div>
          <div class="body">
            <div class="dropdown-divider"></div>

            <b><mark> No tiene suficientes privilegios</mark></b> para cargar opcion solicitada.
            <br>
            <small>Para poder acceder, debes loguearte con un usuario con privilegios necesarios.</small>
            <div class="dropdown-divider"></div>
            <div class="col">
              <a href="{% url 'bases:home' %}" class="btn btn-success"><span class="fa fa-home"></span> Ir al Inicio</a>
              <a href="{% url 'bases:login' %}" class="btn btn-success"><span class="fa fa-user"></span> Ingresar con
                otro Usuario</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>


{% endblock page_content %}