calificaciones/bases/urls.py
from django.urls import include, path
from calificaciones.bases.views import *
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="bases/login.html"),name='logout'),
    path('register/',UserNew.as_view(),name="register"),
    path('sin_privilegios/',HomeSinPrivilegios.as_view(),name="sin_privilegios")
]

calificaciones/users/urls.py
from django.urls import path

from calificaciones.users.views import (
    UserListView,
    UserNew,
    UserEdit,
    UsuarioInactivar,
    perfil

)

app_name = "users"
urlpatterns = [

    path("",UserListView.as_view(),name='user_list'),
    path("create",UserNew.as_view(),name='user_new'),
    path('estado/<int:id>',UsuarioInactivar, name="user_inactivar"),
    path('porfile/<int:id>',perfil,name="user_perfil"),
    path("edit/<int:pk>",UserEdit.as_view(),name='user_edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    #path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    #path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path('',include(('calificaciones.bases.urls','bases'),namespace='bases')),
    path('materias',include(('calificaciones.materias.urls','materias'),namespace='materias')),
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("calificaciones.users.urls", namespace="users")),
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# API URLS
urlpatterns += [
    # API base url
    #path("api/", include("config.api_router")),
    # DRF auth token
    #path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

calificaciones/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth import get_user_model
from django.utils import timezone

from django.contrib.auth.hashers import make_password


class AccountManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, name, phone, password, **extra_fields):
        values = [email, name, phone]
        field_value_map = dict(zip(self.model.REQUIRED_FIELDS, values))
        for field_name, value in field_value_map.items():
            if not value:
                raise ValueError('The {} value must be set'.format(field_name))

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            name=name,
            phone=phone,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, name, phone, password, **extra_fields)

    def create_superuser(self,email,  name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, name, phone, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(auto_created=True,primary_key=True,unique=True, serialize=False)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=150,null=True,blank=True)
    phone = models.CharField(max_length=50,null=True,blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    picture = models.ImageField(blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(null=True)
    username = models.CharField(max_length=255, unique=True,null=True,blank=True)
    apellido = models.CharField(max_length=50,null=True,blank=True)
    dni = models.CharField(max_length=10,null=True,blank=True)

    objects = AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'phone']

    def get_full_name(self):
        return self.name

calificaciones/users/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from calificaciones.users.models import User


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ('email', 'name','apellido', 'phone', 'date_of_birth', 'picture', 'password')

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'name', 'apellido','phone', 'date_of_birth', 'picture', 'password1','password2', 'is_active', 'is_superuser')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(label="Password",
        help_text="Raw passwords are not stored, so there is no way to see "
                  "this user's password, but you can change the password "
                  "using <b><h3><a href=\"../password/\">Click para Cambiar Contraseña</a><h3></b>.")

    class Meta:
        model = User
        fields = ('email', 'name','apellido', 'phone', 'date_of_birth', 'picture', 'password', 'is_active', 'is_superuser')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

calificaciones/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

calificaciones/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse,reverse_lazy
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,render

from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView,ListView,CreateView,View
from calificaciones.bases.views import SinPrivilegios
from calificaciones.users.forms import RegistrationForm,UserCreationForm,UserChangeForm
from calificaciones.users.models import User
from django.contrib.auth.decorators import login_required,permission_required


class UserListView(SinPrivilegios,ListView):
    model = User
    template_name = "users/user_list.html"
    context_object_name = "obj"
    queryset = User.objects.order_by('id')
    permission_required ="users.user_view"


class UserNew(SinPrivilegios, CreateView):
    model= User
    template_name="users/user_new.html"
    context_object_name = "obj"
    form_class= UserCreationForm
    success_url = reverse_lazy("users:user_list")
    permission_required ="users.user_new"

class UserEdit(SinPrivilegios,UpdateView):
    model = User
    template_name = "users/register.html"
    context_object_name = "obj"
    form_class = UserCreationForm
    success_url = reverse_lazy("users:user_list")
    permission_required ="users.user_change"


@login_required(login_url="/login/")
@permission_required("users.user_change",login_url="/login/")
def UsuarioInactivar(request,id):
    user = User.objects.filter(pk=id).first()

    if request.method =="POST":
        if user:
            user.is_active = not user.is_active
            user.save()
            return HttpResponse("OK")
        return HttpResponse("FAIL")
    return HttpResponse("FAIL")




def perfil(request,id):
    template_name = 'users/porfile.html'

    print(id)
    obj = User.objects.get(id=id)
    print(obj)
    if request.method == 'GET':
        context = {"obj":obj}

    return render(request,template_name,context)

calificaciones/users/templates/users/register.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Sign Up | Bootstrap Based Admin Template - Material Design</title>
    <!-- Favicon-->
    <link rel="icon" href="../../favicon.ico" type="image/x-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Bootstrap Core Css -->
    <link href="../../../static/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="../../../static/plugins/node-waves/waves.css" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="../../../static/plugins/animate-css/animate.css" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="../../../static/css/style.css" rel="stylesheet">
</head>

<body class="signup-page">
    <div class="signup-box">
        <div class="logo">
            <a href="javascript:void(0);">Admin<b>BSB</b></a>
            <small>Admin BootStrap Based - Material Design</small>
        </div>
        <div class="card">
            <div class="body">
                <form id="sign_up" method="POST">
                 {% csrf_token %}
                      {{form.as_p}}
                    <div class="msg">Register a new membership</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="username" id="id_username" placeholder="Name Surname" required autofocus>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="first_name" id="id_first_name" placeholder="First Nme" required autofocus>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="last_name" id="id_last_name" placeholder="Last Name" required autofocus>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">email</i>
                        </span>
                        <div class="form-line">
                            <input type="email" class="form-control" name="email" id="id_email" placeholder="Email Address" required>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="password1" id="id_password1" minlength="6" placeholder="Password" required>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="password2" id="id_password2" minlength="6" placeholder="Confirm Password" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="checkbox" name="terms" id="terms" class="filled-in chk-col-pink">
                        <label for="terms">I read and agree to the <a href="javascript:void(0);">terms of usage</a>.</label>
                    </div>

                    <button class="btn btn-block btn-lg bg-pink waves-effect" type="submit">SIGN UP</button>

                    <div class="m-t-25 m-b--5 align-center">
                        <a href="{% url 'bases:login' %}">You already have a membership?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Jquery Core Js -->
    <script src="../../../static/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core Js -->
    <script src="../../../static/plugins/bootstrap/js/bootstrap.js"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="../../../static/plugins/node-waves/waves.js"></script>

    <!-- Validation Plugin Js -->
    <script src="../../../static/plugins/jquery-validation/jquery.validate.js"></script>
    <script src="../../../static/plugins/jquery-validation/localization/messages_es.js"></script>

    <!-- Custom Js -->
    <script src="../../../static/js/admin.js"></script>
    <script src="../../../static/js/pages/examples/sign-up.js"></script>
</body>

</html>

calificaciones/users/templates/users/user_list.html
{% extends 'base/base.html' %}
{% block page_content %}

   <!-- Basic Examples -->
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>
                    LISTADO DE USUARIOS
                </h2>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                <b>TABLA</b>
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <button type="button" class="btn btn-default waves-effect m-r-20" data-toggle="modal" data-target="#defaultModal">MODAL - DEFAULT SIZE</button>
                                        <li><a onclick="return abrir_modal('{% url 'users:user_new' %}')">Nuevo</a></li>

                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            {% if not obj %}
                            <div class="alert alert-info"No Hay Usuarios</div>
                            {% else %}
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Dni</th>
                                            <th>username</th>
                                            <th>Nombres</th>
                                            <th>Apellidos</th>

                                            <th>estado</th>
                                            <th>telefono</th>
                                            <th class="all">Acciones</th>

                                        </tr>
                                    </thead>

                                    <tbody>
                                    {% for item in obj %}
                                    {% if not item.is_staff %}
                                      {% if not item.superuser %}
                                       <tr>
                                            <th>{{item.id}}</th>
                                            <th>{{item.dni}}</th>
                                            <th>{{item.username}}</th>
                                            <th>{{item.name}}</th>
                                            <th>{{item.apellido}}</th>

                                            <td>
                                              <div  onclick="inactivar({{ item.id }})">
                                               {% if item.is_active %}
                                              <div  class="col-sm-3">
                                                <div class="switch" >
                                                    <h4><label><input type="checkbox" checked><span class="lever switch-col-red"></span></label></h4>
                                                </div>
                                            </div>
                                              {% else %}
                                              <div class="col-sm-3">
                                                <div class="switch">
                                                    <label><input type="checkbox" ischecked><span class="lever switch-col-red"></span></label>
                                                </div>
                                            </div>
                                            {% endif %}
                                          </div>
                                          </td>
                                            <th>{{item.phone}}</th>
                                            <th>

                                                <button class="btn bg-light-green btn-circle waves-effect waves-circle waves-float"
                                                  onclick="return abrir_modal('{% url 'users:user_edit' item.id %}')">
                                                 <i class="material-icons">mode_edit</i></i></button>

                                            </th>

                                        </tr>
                                      {% endif %}
                                    {% endif %}

                                    {% endfor %}


                                    </tbody>
                                </table>
                            </div>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Examples -->
            </div>

      </section>
      {% endblock page_content %}
      {% block js %}

      <script>

        function inactivar(id)
        {
          console.log(id)
          var data = {id:id};
          data = JSON.stringify(data);
          var token = '{{ csrf_token }}';+
          console.log(token)
          //alert(token);
          //alert(id);

          $.ajax({
            headers : {"X-CSRFToken":token},
            type:"POST",
            url:"/users/estado/"+id,
            data:data,
            success: function(response){
              if(response==="OK")
              {
                windows.location.reload(true);
              }
              else{
                mensaje("Error Intentando cCambiar Estado a Cliente");
              }
            },
            error:function(jqXHR, textStatus, errorThrow){
              console.log(textStatus,errorThrow);
              mensaje(errorThrow,'red');
              cerrar_modal();
            }
          });
        }
      </script>
      {% endblock js %}

calificaciones/users/templates/users/user_new.html
<div class="modal-dialog modal-lg" >
  <div class="modal-content">
    {% if obj %}
    <form method="POST" role="form" class="form-inline" action="{% url 'users:user_edit' obj.pk %}" >
    {% else %}
    <form method="POST" role="form" class="form-inline" action="{% url 'users:user_new' %}" >
    {% endif %}




<div class="col-xl-12 col-md-12 mb-12">
  <div class="card">

    {% if obj %}
    <div class="header bg-amber">

        {% else %}
        <div class="header bg-light-green">
          {% endif %}

          <h2>
            {% if obj %} Editar {% else %} Nuevo {% endif %} Usuario <small>Description text here...</small>
          </h2>
          <ul class="header-dropdown m-r--5">
              <li>
                  <a href="javascript:void(0);" data-toggle="cardloading" data-loading-effect="rotation" data-loading-color="lightGreen">
                      <i class="material-icons">loop</i>
                  </a>
              </li>
              <li class="dropdown">
                  <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      <i class="material-icons">more_vert</i>
                  </a>
                  <ul class="dropdown-menu pull-right">
                      <li><a href="javascript:void(0);">Action</a></li>
                      <li><a href="javascript:void(0);">Another action</a></li>
                      <li><a href="javascript:void(0);">Something else here</a></li>
                  </ul>
              </li>
          </ul>
      </div>
      <div class="body">
        {% csrf_token %}
          {{form.as_p}}
         <!-- Vertical Layout | With Floating Label -->
         <div class="row clearfix">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <div class="card">
                  <div class="body">

                        <div class="row clearfix">
                        <div class="col-md-3">
                          <div class="form-group form-float">
                              <div class="form-line">
                                  <input type="text" id="id_first_name" name="first_name" value="{{obj.first_name}}" class="form-control">
                                  <label class="form-label">Nombres</label>

                              </div>
                          </div>
                        </div>
                        <div class="col-md-3">
                          <div class="form-group form-float">
                              <div class="form-line">
                                  <input type="text" id="password" name="last_name" id="id_last_name" value="{{obj.last_name}}" class="form-control">
                                  <label class="form-label">Apellidos</label>
                              </div>
                          </div>
                        </div>
                        <div class="col-md-3">
                          <div class="form-group form-float">
                              <div class="form-line">
                                  <input type="text" id="id_username" name="username" value="{{obj.username}}" class="form-control">
                                  <label class="form-label">Nombre de Usuario</label>
                              </div>
                          </div>
                        </div>
                        <div class="col-md-3">
                          <div class="form-group form-float">
                              <div class="form-line">
                                  <input type="email" id="id_email" name="email" value="{{obj.email}}" class="form-control">
                                  <label class="form-label">Correo Electronico</label>
                              </div>
                          </div>
                        </div>
                      </div>
                      <div class="row clearfix">
                        <div class="col-md-3">
                          <div class="form-group form-float">
                              <div class="form-line">
                                  <input type="text"  maxlength="8" id="id_telefono" name="telefono" value="{{obj.telefono}}" class="form-control">
                                  <label class="form-label">Telefono</label>
                              </div>
                          </div>
                        </div>

                        <div class="col-md-3">
                          <div class="form-group form-float">
                              <div class="form-line">
                                  <input type="password" id="id_password1" name="password1" value="{{obj.password1}}" class="form-control">
                                  <label class="form-label">Contraseña</label>
                              </div>
                          </div>
                        </div>
                        <div class="col-md-3">
                          <div class="form-group form-float">
                              <div class="form-line">
                                  <input type="password" id="id_password2" name="password2" value="{{obj.password2}}" class="form-control">
                                  <label class="form-label">Comtraseña(confirmar)</label>
                              </div>
                          </div>
                        </div>

                          <div class="col-md-3">
                            <div class="form-group">
                             <input type="checkbox" id="id_is_active" name="is_active" value="{{obj.is_active}}" >
                              <label for="id_is_active">Estado</label>


                          </div>
                        </div>
                      </div>



                  </div>
              </div>
          </div>
      </div>
      <!-- Vertical Layout | With Floating Label -->


      </div>
      <div class="footer">
        <div class="modal-footer"  >

          <button type="submit" class="btn btn-danger waves-effect"><i class="material-icons">save</i><span class="icon-name">Guardar</span></button>
          <button type="button" class="btn btn-success waves-effect" onclick="return cerrar_modal()"><i class="material-icons">cancel</i> <span class="icon-name">Cancelar</span></button>
      </div>
      </div>
  </div>
</div>
</form>
</div>
</div>



<!-- Custom Js -->

<script src="../../../static/js/admin.js"></script>